package chksum;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.bind.DatatypeConverter;

public class chksum extends javax.swing.JFrame {

    File file1, file2, file3;
    String hash1, hash2, hash3;
    static String komentar;
    MessageDigest digest;
    
    private static String getFileChecksum(MessageDigest md, File file) {
        
        try {
            md.update(Files.readAllBytes(file.toPath()));
        } catch (IOException ex) { Logger.getLogger(chksum.class.getName()).log(Level.SEVERE, null, ex);
        }
        byte[] digest = md.digest();
        
        String res = DatatypeConverter.printHexBinary(digest) ;
        return res;

}

    public chksum() {
        initComponents();
        jHash1.setEditable(false);
        jHash2.setEditable(false);
        jHash3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jfileSelect1 = new javax.swing.JButton();
        jfileSelect2 = new javax.swing.JButton();
        jFilePath1 = new javax.swing.JTextField();
        jfilePath2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jHashFunckija = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jIzracunajHash = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jHash1 = new javax.swing.JTextField();
        jHash2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFileSelect3 = new javax.swing.JButton();
        JFilePath3 = new javax.swing.JTextField();
        jHashFunckija2 = new javax.swing.JComboBox();
        jHashIzracunat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jIzracunajHash2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jHash3 = new javax.swing.JTextField();
        jStatus1 = new javax.swing.JLabel();
        jStatus2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfileSelect1.setText("File Select 1");
        jfileSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfileSelect1ActionPerformed(evt);
            }
        });

        jfileSelect2.setText("File Select 2");
        jfileSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfileSelect2ActionPerformed(evt);
            }
        });

        jFilePath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFilePath1ActionPerformed(evt);
            }
        });

        jHashFunckija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MD5", "SHA-256" }));
        jHashFunckija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHashFunckijaActionPerformed(evt);
            }
        });

        jLabel1.setText("Hash Funkcija: ");

        jIzracunajHash.setText("Izracunaj Hash");
        jIzracunajHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIzracunajHashActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel2.setText("Status:");

        jHash1.setText("Hash 1");

        jHash2.setText("Hash 2");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setAutoscrolls(true);
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setText("Compare 2 Files:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setText("Compare Hash and File:");

        jFileSelect3.setText("File Select");
        jFileSelect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileSelect3ActionPerformed(evt);
            }
        });

        jHashFunckija2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MD5", "SHA-256", "SHA-1" }));
        jHashFunckija2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHashFunckija2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Porediti Hash sa:");

        jLabel6.setText("Hash Funkcija: ");

        jIzracunajHash2.setText("Izracunaj Hash");
        jIzracunajHash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIzracunajHash2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel7.setText("Status:");

        jHash3.setText("Hash ");

        jStatus1.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jStatus1.setText("         ");

        jStatus2.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jStatus2.setText("         ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jfileSelect1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFilePath1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jfileSelect2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jfilePath2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(jHashFunckija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jIzracunajHash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jHash1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jHash2)
                            .addComponent(jSeparator3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jFileSelect3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHashIzracunat)
                            .addComponent(JFilePath3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHashFunckija2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jIzracunajHash2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHash3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel4)))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfileSelect1)
                    .addComponent(jFilePath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfileSelect2)
                    .addComponent(jfilePath2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHashFunckija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jIzracunajHash)
                    .addComponent(jLabel2)
                    .addComponent(jStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHash1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHash2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileSelect3)
                    .addComponent(JFilePath3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHashIzracunat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHashFunckija2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jIzracunajHash2)
                    .addComponent(jLabel7)
                    .addComponent(jStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfileSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfileSelect1ActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            file1 = jfc.getSelectedFile();
            jFilePath1.setText(file1.getAbsolutePath());
        }

    }//GEN-LAST:event_jfileSelect1ActionPerformed

    private void jfileSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfileSelect2ActionPerformed

        JFileChooser jfc = new JFileChooser();
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            file2 = jfc.getSelectedFile();
            jfilePath2.setText(file2.getAbsolutePath());
        }

    }//GEN-LAST:event_jfileSelect2ActionPerformed

    private void jFilePath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFilePath1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFilePath1ActionPerformed

    private void jHashFunckijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHashFunckijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHashFunckijaActionPerformed

    private void jIzracunajHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIzracunajHashActionPerformed
        try {
            String hashfun = jHashFunckija.getSelectedItem().toString();
            
            MessageDigest digest = MessageDigest.getInstance(hashfun);
            
            hash1 = getFileChecksum(digest, file1);
            hash2 = getFileChecksum(digest, file2);
            
            if(hash1.equals(hash2)){
                jStatus1.setText("Equal");
            } else {
                jStatus1.setText("Not Equal");
            }
            
            jHash1.setText(hash1);
            jHash2.setText(hash2);
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(chksum.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_jIzracunajHashActionPerformed

    private void jFileSelect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileSelect3ActionPerformed
       // File3
        JFileChooser jfc = new JFileChooser();
        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            file3 = jfc.getSelectedFile();
            JFilePath3.setText(file3.getAbsolutePath());
      
        }
        
        
        
    }//GEN-LAST:event_jFileSelect3ActionPerformed

    private void jHashFunckija2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHashFunckija2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHashFunckija2ActionPerformed

    private void jIzracunajHash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIzracunajHash2ActionPerformed

        try {
            
            String hashfun = jHashFunckija2.getSelectedItem().toString();
            
            MessageDigest digest = MessageDigest.getInstance(hashfun);
            
            hash3 = getFileChecksum(digest, file3);
            
            if(hash3.equals(jHashIzracunat.getText())){
                jStatus2.setText("Equal");
            } else {
                jStatus2.setText("Not Equal");
            }
            
            jHash3.setText(hash3);
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(chksum.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            String hashfun = jHashFunckija2.getSelectedItem().toString();
            jHash3.setText(hash3);
        }

    }//GEN-LAST:event_jIzracunajHash2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chksum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chksum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chksum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chksum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chksum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JFilePath3;
    private javax.swing.JTextField jFilePath1;
    private javax.swing.JButton jFileSelect3;
    private javax.swing.JTextField jHash1;
    private javax.swing.JTextField jHash2;
    private javax.swing.JTextField jHash3;
    private javax.swing.JComboBox jHashFunckija;
    private javax.swing.JComboBox jHashFunckija2;
    private javax.swing.JTextField jHashIzracunat;
    private javax.swing.JButton jIzracunajHash;
    private javax.swing.JButton jIzracunajHash2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jStatus1;
    private javax.swing.JLabel jStatus2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jfilePath2;
    private javax.swing.JButton jfileSelect1;
    private javax.swing.JButton jfileSelect2;
    // End of variables declaration//GEN-END:variables
}
